### ISSUE TITLE
Failed to start the tunnel

### ISSUE THREAD

**Issue by gilfuser** [azratul/live-share.nvim#2]
Hi, I hope you are fine and well.

I'm trying to use this very promissing plugin. Thank you for the great project.

I'm having issues to understand the README.

I used the lazy example:
```
{
  "azratul/live-share.nvim",
  dependencies = {
    "jbyuki/instant.nvim",
  },
  config = function()
    vim.g.instant_username = "my_name"
    require("live-share").setup({
      port_internal = 8765,
      max_attempts = 40, -- 10 seconds
      service = "serveo.net"
    })
  end
}
```
I restarted neovim, opened the file I want to share and did the command `:LiveShareServer`

I got the following error:
`  Error  01:49:07 PM msg_show.emsg Failed to start the tunnel`
but tried to join in another computer. I installed live-share.nvim in the same way, but then didn't know exactly how to join. Should I use the IP from the first machine or should I use abc.serveo.net as in the example? Both machines are in the same network, b.t.w.
What is serveo.net?

I appreciate any pointers about this.

thank you again,
Gil

**Comment by azratul** [comment]
Hi,

Serveo.net is a service for creating reverse tunnels to expose specific services. In your case, Serveo was most likely down, as it tends to have irregular uptime. I recommend trying a simpler configuration and using localhost.run instead of serveo.net. Here's an example:

```
{
  "azratul/live-share.nvim",
  dependencies = {
    "jbyuki/instant.nvim",
  },
  config = function()
    vim.g.instant_username = "gil_testing"
    require("live-share").setup({
      max_attempts = 40,
      service = "localhost.run"
    })
  end
}
```

As for its usage, it's just as shown in the GIF in the README. You need to wait for the server to start and connect to the service (which will now be localhost.run). Once connected, a message will appear saying "The URL has been copied to the clipboard." This is the URL you need to share with anyone who wants to connect to your Neovim server. On the other instance, you can join by using `:LiveShareJoin your-url`.

If you have any other questions, feel free to ask.

Best regards,

**Comment by gilfuser** [comment]
Hi. Thank you for your prompt response. I'm still getting the `Failed to start the tunnel` message. Do I need to configure localhost.run somehow?

**Comment by azratul** [comment]
I have a suspicion that the README doesn't mention the need to have SSH installed beforehand, so I'll be adding that right away. What OS are you using? So far, the plugin has been successfully tested on multiple Linux distros and OpenBSD, but it hasn’t been tested on macOS or Windows yet. If, after installing SSH (if you didn’t already have it), you’re still experiencing issues, try running the following command:

```
ssh -R 80:localhost:8080 nokey@localhost.run
```

This should return a QR code and a URL. If it doesn’t work, your ISP or network admin might be blocking the connection. You could also try using a different port that isn’t already in use on your host.

**Comment by gilfuser** [comment]
Hi again.
I'm using Ubuntu Studio 24.04.
I already have SSH and did evaluate the line you mentioned:
` ssh -R 80:localhost:8080 nokey@localhost.run ` 
I got the qr code and all, but I didn't know what to do with it.

Thank you for keeping up with me

**Comment by azratul** [comment]
Alright, I'm starting to run out of ideas. The issue is clear: the tunnel isn’t being established for some reason. If the command I sent you works, then it’s either latency or a port issue. Try using port 8080 since you’ve already confirmed that it works. Keep your config as follows:

```
{
  "azratul/live-share.nvim",
  dependencies = {
    "jbyuki/instant.nvim",
  },
  config = function()
    vim.g.instant_username = "gil_testing"
    require("live-share").setup({
      port_internal = 8080,
      max_attempts = 120,
      service = "localhost.run"
    })
  end
}
```

This sets port 8080 as the listening port and will wait for a response from the localhost.run server for 30 seconds.

**Comment by gilfuser** [comment]
Hi again.
I had no luck. I even tried with ngrok instead of localhost.run, but I have no experience with it, so I couldn't go very far.

Thank you anyway. I'll stay tuned.

**Comment by azratul** [comment]
Apologies for the delayed response, but I just gained access to a machine running Ubuntu Studio today, where I was able to replicate and fix the issue. Please make sure to update the plugin before trying again and let me know if you're still encountering any problems. For some reason, on Ubuntu Studio, you need to use **nokey@localhost.run** instead of just **localhost.run**. Try the following configuration:

```
{
  "azratul/live-share.nvim",
  dependencies = {
    "jbyuki/instant.nvim",
  },
  config = function()
    vim.g.instant_username = "gil_testing"
    require("live-share").setup({
      max_attempts = 40,
      service = "nokey@localhost.run"
    })
  end
}
```

Let me know how it goes!

**Comment by azratul** [comment]
Hey @gilfuser,

Just checking in – I believe the issue is fixed, so I'm going to close it out since I haven't heard back from you.

If you're still having any trouble, feel free to reopen the issue or open a new one, and I'll be happy to help!

Thanks!

**Comment by azratul** [comment]
Hey @gilfuser,

Just checking in – I believe the issue is fixed, so I'm going to close it out since I haven't heard back from you.

If you're still having any trouble, feel free to reopen the issue or open a new one, and I'll be happy to help!

Thanks!
